apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-frontend
  labels:
    app: mlops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-frontend
  template:
    metadata:
      labels:
        app: mlops-frontend
    spec:
      containers:
      - name: mlops-frontend
        image: mlops-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-frontend-service
spec:
  selector:
    app: mlops-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
