database:
  database: alter_managment
  host: localhost
  password: root
  port: 3306
  prediction_table: orders_pred
  training_table: smoke_detection_iot
  type: mysql
  user: root
preprocessing:
  script_path: src/features/dummy_preprocess.py
mlflow:
  experiment_name: test_dynamic_preprocessing
  tracking_uri: http://localhost:5000
model:
  name: RandomForestClassifier
  params:
    n_estimators: 10
  target_col: Fire Alarm
  task_type: classification
